### ISSUE TITLE
A JS error occurs on some surveys

### ISSUE THREAD

**Issue by mmcev106** [vanderbilt-redcap/cross-project-piping-module#1]
From Ed Morales:

> This is Ed Morales from Partners Healthcare in Boston, Ma. We scan, test, troubleshoot, debug, all external modules we're considering releasing to our Production environment and recently a user requested your external module: cross project piping. As with most external modules in the REDCap repo, you external module is very stable and it meets its expectations. You will find all the documentation we generated from reviewing it attached to this email.
>
>We found a bug, in projects that have this ext-mod enabled, that renders surveys un-useable. You will find the recreation steps in the attached documents. We got around the issue by removing the permission to redcap_survey_top and preventing the ext-mod from running on surveys.
>
> Our goal of sharing this information with you is to keep you in the loop of our findings. Please do not rush to fix this for us as we have already address the issue. Our goal is to provide you helpful and friendly feedback.
>
> Thanks and let us know if we can be of any help.

**Comment by carlreedw** [comment]
I've just pushed a commit (tagged v1.3.1) to the module that adds a "allow-piping-on-survey-pages" setting. When this is checked, piping will work on survey pages, but only if the checkbox is selected. This should prevent issues where survey pages are unexpectedly piped to.
