### ISSUE TITLE
REDCap crash due to an expected PHP fatal error! message

### ISSUE THREAD

**Issue by willid6** [vanderbilt-redcap/cross-project-piping-module#16]
I am on REDCap 12.0.19 PHP 8.06.
When I click "Enable" I get an error (see screenshot). Do you know if this is resolvable? 
![REDCap cross-project piping EM error 20220329](https://user-images.githubusercontent.com/102616996/160671025-fd281377-1aaa-4410-b904-631361f7e643.png)

**Comment by mmcev106** [comment]
It looks like this module needs to be updated to support PHP8.  Unfortunately, it does not have a support budget currently.  Let us know if you're interested in sponsoring it.

**Comment by tertek** [comment]
@mmcev106 
Since we are upgrading to PHP8.1 and we need the module I will try add support for PHP8 to this module.
Going to use phpstan for analyzing the code.
Anything I need to think of from your side?

**Comment by tertek** [comment]
Running phpstan
` vendor/bin/phpstan analyse modules/cross_project_piping_v1.4.9/`

`phpstan.neo`

    parameters:
    level: max
    ignoreErrors:
        -'#Call to an undefined method#'
        -'#Variable \$module might not be defined.#'
        -'# on an unknown class #'
        -'#not found#'
[phpstan.txt](https://github.com/vanderbilt-redcap/cross-project-piping-module/files/9652670/phpstan.txt)

**Comment by tertek** [comment]
I have submitted a PR: https://github.com/vanderbilt-redcap/cross-project-piping-module/pull/18/files
We need the module for a current high-priority project.
