### ISSUE TITLE
support for repeating instruments

### ISSUE THREAD

**Issue by mschulze0** [vanderbilt-redcap/cross-project-piping-module#2]
Hi,

I really like your module however I can't use it quite yet as I want to use it on a repeating instrument. My setup is as follows:
I have a repeating instrument with an SQL field that I fill with patient IDs coming from another project. On the same instrument I have several fields that I fill with cross-project piping using the patient ID selected on the repeating instrument.
The cross-project piping works fine on the first instance of the instrument, however when I create the second instance, select a patient ID and save it, the module not only pipes the data to this instance but also to the previous instance so that the previous instance now contains cross-piped data from an incorrect patient ID.

**Comment by mschulze0** [comment]
Hi,

I guess there is also no support for events?

**Comment by mschulze0** [comment]
Hi,

I guess this is only a problem when the Unique Match Field is on a repeating instrument.

**Comment by mschulze0** [comment]
Just changed the code myself. How can I submit a patch?

**Comment by Enturk** [comment]
@mschulze0 you might take this project over - I'd particularly benefit from that if you fixed it to allow piping **[event]**[field] variables. Maybe @taylorr4 or @scottjpearson or @alewis64 could help with that?

**Comment by carlreedw** [comment]
9463de05e681d78b6f865276f017173f65b8ca6a adds support for repeating instruments/events.

**Comment by mschulze0** [comment]
> [9463de0](https://github.com/vanderbilt-redcap/cross-project-piping-module/commit/9463de05e681d78b6f865276f017173f65b8ca6a) adds support for repeating instruments/events.

great. Will wait until it shows up in the redcap repository.

**Comment by Enturk** [comment]
Could we update the documentation to explain how to access fields in repeating instruments or events? The existing docs show use of field names without square brackets, so it's not clear how one would prepend event names to them, for example.
