### ISSUE TITLE
$newChoices initialized but never used

### ISSUE THREAD

**Issue by aarenson** [vanderbilt-redcap/cross-project-piping-module#5]
In CrossprojectpipingExternalModule.php on line 408, $newChoices is initiatlized, but it is then never used.

**Comment by mmcev106** [comment]
Thanks very much for the report.  The support budget for this module is unfortunately very limited.  I see what you mean in the code.  Does this make the module behave unexpectedly?  If so, are you able to create a PR to fix it?  If not, I may be able to find a way to account for the time...  If it is just an oddity in the code, then we should probably leave it as I have a million other things to do that are more important.

**Comment by aarenson** [comment]
This came up as part of our standard vetting process, during a static code analysis. I don't know of any functional problems associated with this.

**Comment by mmcev106** [comment]
I guess I'll go ahead and close this then.  I still very much appreciate the feedback.  If we had a decent support budget for this module I would go ahead and clarify that in the code...
