### ISSUE TITLE
Is this abandonware?

### ISSUE THREAD

**Issue by Enturk** [vanderbilt-redcap/cross-project-piping-module#9]
It looks like the code has not been updated in over a year, and a user has offered to address an issue, but the request is going unanswered. Maybe someone else should take over this repo?

**Comment by mmcev106** [comment]
This is not abandonware, but maintaining a support budget for this module has been a struggle...  If anyone is willing & able to take over support for this module, that would be fantastic!  I'm now watching this repo, and will at least take over communication on issues & PRs.

Is the issue you were referring to PR #3?  If so, this has been addressed in the code, and I have reached out the person who made that change about releasing a new version.

**Comment by Enturk** [comment]
That is the issue I was referring to. In that issue, you might ask if @mschulze0 is willing to participate in actively maintaining this repo, since you guys don't seem to have the funds or bandwidth to (and that's not a dig - we do what we can do).

I've seen the update you reference here, but it has not propagated into the REDCap module library. Since that's how most people actually use the module, only updating it here might not be sufficient. I assume that you don't have the funding/bandwidth/capacity to trigger that propagation. What would it cost to make that happen?

**Comment by mmcev106** [comment]
I've already reached out @carlreedw and plan to discuss releasing a new version to the Repo with him.  This doesn't take long, but it's of course important to take great care in what we release to make sure we don't break existing functionality for anyone (especially when we don't have the support budget to quickly address any potential issues).

I just sent @mschulze0 [this message](https://github.com/vanderbilt-redcap/cross-project-piping-module/pull/3#issuecomment-779345208) per your recommendation.

**Comment by Enturk** [comment]
Just to be clear, my suggestion is that you make @mschulze0 one of the repo contributors, or anyone else who seems qualified and willing to take over its maintenance, just because you guys don't seem to have the bandwidth and funding to do so.

**Comment by mmcev106** [comment]
Yes, that suggestion was clear the first time around.  We would need to get to know @mschulze0 a little bit better beforehand (likely through PRs), since module support has security implications (especially this module).

**Comment by Enturk** [comment]
That's entirely reasonable, and she may not want to do more than offer up
the occasional request, in which case please don't kidnap him or her and
coerce them to maintain this repo.

So, yes.

**Comment by mschulze0** [comment]
Hi @mmcev106, @Enturk,

I can only contribute to this module (or any other REDCap EMs) to the extent it's necessary for my main work (which is mainly scientific, and software development only if it's necessary for me).

**Comment by Enturk** [comment]
Well, that does support the notion that you're qualified to do just that, @mschulze0 .
